name: signals_slots
description: An implementation of a managed signals and slots system based on the boost signals2 C++ library.
version: 1.1.0
repository: https://github.com/voidari/flutter_signals_slots
issue_tracker: https://github.com/voidari/flutter_signals_slots/issues

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# The following section is specific to Flutter packages.
flutter: